import { defineProject, type Project } from "@/lib/types";

/**
 * Client builds shown as cards on /work without a dedicated case study — real
 * shipped work, but where the interesting engineering is already covered by one
 * of the full case studies.
 *
 * Live URLs here were each verified as returning 200. Anything password-gated
 * or no longer serving is marked accordingly and renders without a link, rather
 * than sending a visitor to an error page.
 */
export const clientCards: readonly Project[] = [
  defineProject({
    slug: "adapthealth-diabetes",
    name: "AdaptHealth Diabetes",
    tagline: "Insurance-billed diabetes supplies, on a recurring cadence",
    vertical: "healthcare",
    depth: "card",
    order: 20,
    year: "2025 — 2026",
    role: "Frontend engineer",
    liveStatus: "live",
    url: "https://diabetes.adapthealth.com",
    stack: ["Shopify Liquid", "TypeScript", "Azure MSAL", "GSAP", "IndexedDB"],
    metrics: [],
    summary:
      "CGMs and test strips sold through insurance rather than retail. Shares the authenticated-ordering foundation built for the wider AdaptHealth estate, with a resupply cadence layered on top.",
  }),
  defineProject({
    slug: "10x-health-system",
    name: "10X Health System",
    tagline: "Precision wellness diagnostics and protocols",
    vertical: "healthcare",
    depth: "card",
    order: 21,
    year: "2026",
    role: "Frontend engineer",
    liveStatus: "live",
    url: "https://10xhealthsystem.com",
    stack: ["Shopify Liquid", "TypeScript", "Playwright", "pixelmatch"],
    metrics: [],
    summary:
      "The consumer-facing half of the 10X estate. Where the visual regression harness described in the 10X Health Network case study actually runs.",
  }),
  defineProject({
    slug: "cx-ortho-supply",
    name: "CX Orthodontic Supply",
    tagline: "B2B ordering for practices that reorder the same things",
    vertical: "b2b",
    depth: "card",
    order: 22,
    year: "2025",
    role: "Frontend engineer",
    liveStatus: "live",
    url: "https://cxorthosupply.com",
    stack: ["Shopify Liquid", "TypeScript", "Svelte", "lazysizes"],
    metrics: [],
    summary:
      "Dental and orthodontic supply for practices. B2B reordering rewards speed and predictability over discovery — dense catalogue, fast repeat paths, no decoration.",
  }),
  defineProject({
    slug: "jatai-international",
    name: "Jatai International",
    tagline: "Professional grooming tools, distributor catalogue",
    vertical: "b2b",
    depth: "card",
    order: 23,
    year: "2025",
    role: "Frontend engineer",
    liveStatus: "live",
    url: "https://jatai.net",
    stack: ["Shopify Liquid", "TypeScript", "Svelte", "Framer Motion"],
    metrics: [],
    summary:
      "US distributor for Japanese professional beauty and grooming brands. A deep, specification-heavy catalogue serving trade buyers who know exactly what they came for.",
  }),
  defineProject({
    slug: "nouveau-contour",
    name: "Nouveau Contour USA",
    tagline: "Devices, pigments and the training course that sells them",
    vertical: "b2b",
    depth: "card",
    order: 24,
    year: "2025",
    role: "Frontend engineer",
    liveStatus: "live",
    url: "https://www.nouveaucontourusa.com",
    stack: ["Shopify Liquid", "TypeScript", "Svelte", "GSAP"],
    metrics: [],
    summary:
      "Permanent-makeup equipment sold alongside certification training. Two audiences with different intent — practitioners restocking and newcomers being convinced — on one storefront.",
  }),
  defineProject({
    slug: "chill",
    name: "Chill",
    tagline: "One brand, three storefronts, shared foundation",
    vertical: "ecommerce",
    depth: "card",
    order: 25,
    year: "2025 — 2026",
    role: "Frontend engineer",
    liveStatus: "live",
    url: "https://chill.com",
    stack: ["Shopify Liquid", "TypeScript", "Svelte", "webpack 5", "Playwright"],
    metrics: [],
    summary:
      "Functional supplements across a US storefront, a UK storefront and a gated wholesale channel. The interesting part is keeping three deployments on one codebase without forking the theme three ways.",
  }),
  defineProject({
    slug: "fire-the-imagination",
    name: "Fire The Imagination",
    tagline: "Seasonal retail, where traffic arrives all at once",
    vertical: "ecommerce",
    depth: "card",
    order: 26,
    year: "2025",
    role: "Frontend engineer",
    liveStatus: "live",
    url: "https://firetheimagination.ca",
    stack: ["Shopify Liquid", "TypeScript", "Svelte", "Framer Motion", "PhotoSwipe"],
    metrics: [],
    summary:
      "Canadian party and costume retail — a business whose entire year happens in a few weeks. Also shipped a companion app handling client-side checkout eligibility rules.",
  }),
  defineProject({
    slug: "kimia",
    name: "Kimia",
    tagline: "A legacy jQuery and Vue theme, inherited",
    vertical: "ecommerce",
    depth: "card",
    order: 27,
    year: "2025",
    role: "Frontend engineer",
    liveStatus: "live",
    url: "https://kimia-wellness.com",
    stack: ["Shopify Liquid", "Vue", "jQuery", "TypeScript"],
    metrics: [],
    summary:
      "Natural nutrition retail on a theme carrying both Vue and jQuery from earlier eras. Worth listing because most real frontend work is this: shipping features in a codebase you would not have started this way.",
  }),
  defineProject({
    slug: "grandstand-sox",
    name: "Grandstand Sox",
    tagline: "An accessibility pass on a small storefront",
    vertical: "ecommerce",
    depth: "card",
    order: 28,
    year: "2026",
    role: "Frontend engineer",
    liveStatus: "live",
    url: "https://grandstandsox.com",
    stack: ["Shopify Liquid", "WCAG 2.1 AA"],
    metrics: [],
    summary:
      "Apparel retail, taken through a focused WCAG 2.1 AA remediation — keyboard paths, focus visibility, contrast and announced state changes across the buying flow.",
  }),
  defineProject({
    slug: "betallic",
    name: "Betallic",
    tagline: "Wholesale catalogue, thousands of SKUs",
    vertical: "b2b",
    depth: "card",
    order: 29,
    year: "2025",
    role: "Frontend engineer",
    liveStatus: "live",
    url: "https://betallic.com",
    stack: ["Shopify Liquid", "TypeScript"],
    metrics: [],
    summary:
      "Balloon and party goods wholesale. A catalogue large enough that filtering and pagination performance is the product, not a detail of it.",
  }),
  defineProject({
    slug: "sproos-life",
    name: "Sproos Life",
    tagline: "Supplements storefront with Svelte islands",
    vertical: "ecommerce",
    depth: "card",
    order: 30,
    year: "2025",
    role: "Frontend engineer",
    // sprooslife.com currently returns HTTP 402 — the Shopify store is no
    // longer being served, so there is nothing to link to.
    liveStatus: "offline",
    stack: ["Shopify Liquid", "TypeScript", "Svelte", "PhotoSwipe"],
    metrics: [],
    summary:
      "Supplements retail on the shared island architecture. The storefront is no longer serving, so it is listed without a link.",
  }),
  defineProject({
    slug: "shoptrade",
    name: "ShopTrade",
    tagline: "The agency's own site",
    vertical: "b2b",
    depth: "card",
    order: 31,
    year: "2026",
    role: "Frontend engineer",
    liveStatus: "live",
    url: "https://shoptrade.co.in",
    stack: ["Shopify Liquid", "TypeScript", "video.js", "Playwright"],
    metrics: [],
    summary:
      "Where I work. Building your own agency site is its own genre of problem — everyone has an opinion and nobody is the client.",
  }),
  defineProject({
    slug: "xgen-ai",
    name: "XGen AI",
    tagline: "A Shopify admin app, not a storefront",
    vertical: "product",
    depth: "card",
    order: 32,
    year: "2025",
    role: "Frontend engineer",
    liveStatus: "live",
    url: "https://www.xgen.ai",
    stack: ["React", "Shopify Polaris", "App Bridge", "Web Pixels Extension"],
    metrics: [],
    summary:
      "An AI merchandising product living inside the Shopify admin. Polaris and App Bridge rather than a theme — a genuinely different discipline, where the design system is someone else's and the constraints are the point.",
  }),
];
